alloy:
  configMap:
    # https://grafana.com/docs/alloy/latest/collect/logs-in-kubernetes/
    content: |
      // loki.source.kubernetes_events tails events from the Kubernetes API and converts them
      // into log lines to forward to other Loki components.
      loki.source.kubernetes_events "cluster_events" {
        job_name   = "integrations/kubernetes/eventhandler"
        log_format = "json"
        forward_to = [
          loki.process.cluster_events.receiver,
        ]
      }

      // loki.process receives log entries from other loki components, applies one or more processing stages,
      // and forwards the results to the list of receivers in the component's arguments.
      loki.process "cluster_events" {
        stage.static_labels {
          values = {
            cluster = "moto-a1",
            job = "k8s-events",
          }
        }
      
        stage.json {
          expressions = {
            type = "",
            node = "reportinginstance",
          }
        }
        stage.labels {
          values = {
            type = "",
            node = "",
          }
        }
      
        forward_to = [loki.write.vl.receiver]
      }
      
      loki.write "vl" {
        endpoint {
          url = "http://vl-victoria-logs-single-server.victoria-logs.svc.cluster.local:9428/insert/loki/api/v1/push?_msg_field=msg&_stream_fields=job,cluster"
        }
      }

crds:
  create: false

image:
  pullPolicy: Always

controller:
  type: deployment
