apiVersion: v1
kind: Secret
metadata:
    name: ns
    namespace: ns-system
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    db-password: ENC[AES256_GCM,data:F8v6fd3B/t7Ol2vqCnu9oGzPdzfV7k2McfEGSUkfUFU=,iv:dAP47no2I2B1udgqgFPuPpijp0sZalZSFz+YYjVOtfo=,tag:r3407eEq3Z5b/G0c6waNgA==,type:str]
    mariadb-password: ENC[AES256_GCM,data:lxLFGFlAb+47XNPZ5Zf48KwH/2ZCYNVfa5lLbSdo7U8=,iv:+6K/aNotHyr+NZ72tqNaQB8MaEteRqv/h71A+0D+oPI=,tag:RXZFSsEYbwXu7doXQFO40g==,type:str]
    mongodb-password: ENC[AES256_GCM,data:ZivsBCBlGo4iNe4aRun+12daOUUYaU6rOKtnZhdZxfs=,iv:IK5NTMCv/dKBezqPclbD05n9y96KTBgqdDwFYbma6hI=,tag:8/7Ls7Jv/j3d1/VnxDLf8A==,type:str]
    s3-access-key: ENC[AES256_GCM,data:VZz3ghS00uzmu0bcaCrLNpLo+pk=,iv:jKqN7akxCFFKmrKlqZFiJ5syhstma10yOSGVBNQNfYo=,tag:DwAAZU7ShuW7aCA2Kc/Cjw==,type:str]
    s3-access-secret: ENC[AES256_GCM,data:CzjiOCq+p+5rEGqt3ktbNcqT7peLGtxGq8bb0afGNIcG4UtKncZY5w==,iv:gvnJYy4n8U6EWSNIzMtfmFP+7dg0ieLj36CUlZqChEU=,tag:q4bOJTuJQt00dev82Bv0Bg==,type:str]
    registry-password: ENC[AES256_GCM,data:/3DW3MbYOu0eK3cxKKNu+IkdyRFwv3L/T7xmtPxEH50=,iv:Whx84RiGxoL61xfm+zfa14mjH2KWlqhhbDEdezByQAg=,tag:VgQKU24+cEhsYGGhyjPFUg==,type:str]
    gitea-token: ENC[AES256_GCM,data:8k621f7Mq1wKGtxbUBy0z4Y+tlNk4vnhh1q2ImarRyGZeCcdywqqQw==,iv:qcmSSOYYsKNtJckwHo6EGEsHWe0iC2kBhMXXlwU0ItU=,tag:wp9zSuXri77hRUMlPRtbmQ==,type:str]
    controller-token: ENC[AES256_GCM,data:Hplic7+0l9rputsD5HgLTmyA/EkMTzhIg+fbdovYZLJDGd0HYqrHVMsm7g==,iv:TRs0WUIYaxmv3Z7q6lVPCu51I+onK3a9biWyVfocK24=,tag:rl+zgg+1lMVP426orqnj9g==,type:str]
sops:
    age:
        - recipient: age1g2rwkffct3veu3zl5a09cny4qgjw5he9drdxjwxqclzq6fa0ldtql4kxvd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TS8vc0VjWG5xQVB3NUtl
            OGQ0dzhpalpQYWVPY2lhYWdMYzZNL2RRVkNBCjlmOUFDU1l4Q2Q5TnV0TjlqTG1P
            WExGVEI1bDZvd0ZrODd5Nlo3UE9UN0UKLS0tIHBZT05aRmltTkFnUFVWNmxKS3h6
            NThJK2VRRTcvZVVNT2VmNXd3WlhHdGsKRRxKo+LjVR0BK72Ugth+aHrFA4q7km+q
            FYwSrKM5apWokWktV2xfeA0mRH/R/WYa826CY4GYihxAnuAEuq1JzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-06T13:05:33Z"
    mac: ENC[AES256_GCM,data:2pwcMaJm23Qpr8qpNTg9MS4gOnnrS8jtssmQJyI33eBcX4ZuX3dsWr30zLgiIvKi2zYf/DR/zOuqxIGYnZiKQunQKUQY8BzFLbC/RzMK4Rt+BHs0hJ6fV9Y5G/r3earQ9PkTGkq4CM4ZwaAzVf7GEtYjBPH9MCnF4GgJlIdOJt8=,iv:PewBHtPzKSZnJhSvpQoXOxwZ2OxozYSWtd4GO8bOANg=,tag:dJ5fvgZsKFFy3z2v7L3nqA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
