{
 "title": "Alert / Domain",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "説明",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "期限まで3日を切るとアラートが鳴ります\n\n5分毎に検証するので若干のラグがあります"
   }
  },
  {
   "title": "ドメイン有効期限",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    { "expr": "domain_expiry_days", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Valid",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "targets": [
    {
     "expr": "(round(domain_expiry_days * 86400 + time(), 86400) - 9 * 3600) * 1000 unless domain_probe_success == 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Invalid",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "targets": [
    { "expr": "domain_probe_success == 0", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Total Probe Targets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(max(domain_probe_success) by (instance))"
    }
   ]
  }
 ]
}