{
 "title": "Alert / Certificates",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "説明",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "期限まで１週間を切るとアラートが鳴ります\n\n５分毎に証明書を検証するので若干のラグがあります"
   }
  },
  {
   "title": "Time Until Expiry Date",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "A",
     "crit": "0",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "ssl_cert_not_after - time() < 86400 * 317",
     "legendFormat": "{{ instance }}",
     "units": "none",
     "valueHandler": "Text Only"
    }
   ]
  },
  {
   "title": "Valid",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "A",
     "crit": "0",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "ssl_cert_not_after{dnsnames!=\"\"} * 1000",
     "legendFormat": "{{instance}}",
     "units": "none",
     "valueHandler": "Text Only"
    }
   ]
  },
  {
   "title": "Invalid",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "A",
     "crit": "0",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "ssl_tls_connect_success == 0",
     "legendFormat": "{{ instance }}",
     "units": "none",
     "valueHandler": "Text Only"
    }
   ]
  },
  {
   "title": "Total Probe Targets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(ssl_cert_not_after) by (instance))"
    }
   ]
  },
  {
   "title": "Total Unique Certificates",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(ssl_cert_not_after) by (issuer_cn,serial_no))"
    }
   ]
  }
 ]
}