{
 "title": "Nodes / node_exporter Details",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "node_uname_info" },
    { "expr": "node_os_info" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(node_cpu_online)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))"
    },
    {
     "expr": "count(sum by (cpu) (node_cpu_seconds_total{mode=\"idle\"}))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (mode) (irate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "count(sum by (cpu) (node_cpu_seconds_total{mode=\"idle\"}))",
     "legendFormat": "cpu count"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "targets": [
    {
     "expr": "rate(node_context_switches_total[5m])",
     "legendFormat": "Context Switches"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(node_load1)", "legendFormat": "load1" },
    { "expr": "sum(node_load5)", "legendFormat": "load5" },
    { "expr": "sum(node_load15)", "legendFormat": "load15" }
   ]
  },
  {
   "title": "CPU Usage per Core",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (cpu) (sum by (cpu) (irate(node_cpu_seconds_total{mode!=\"idle\"}[5m])))",
     "legendFormat": "{{ cpu }}"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "targets": [
    {
     "expr": "rate(node_vmstat_pgmajfault[5m])",
     "legendFormat": "Major Page Faults"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Used"
    },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Cached_bytes - node_memory_Buffers_bytes - node_memory_Slab_bytes",
     "legendFormat": "Used"
    },
    { "expr": "node_memory_Buffers_bytes", "legendFormat": "Buffers" },
    { "expr": "node_memory_Cached_bytes", "legendFormat": "Cached" },
    { "expr": "node_memory_Slab_bytes", "legendFormat": "Slab" },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free" },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes - node_memory_SwapCached_bytes - node_memory_SwapFree_bytes",
     "legendFormat": "Used"
    },
    { "expr": "node_memory_SwapCached_bytes", "legendFormat": "Cached" },
    { "expr": "node_memory_SwapFree_bytes", "legendFormat": "Free" },
    { "expr": "node_memory_SwapTotal_bytes", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Swap Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_SwapTotal_bytes" }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!~\"lo|bond[0-9]|cbr[0-9]|veth.*|br-.*|docker.*|flannel.*|cni.*\"}[5m]) * 8 > 0",
     "legendFormat": "{{device}} (in)"
    },
    {
     "expr": "-irate(node_network_transmit_bytes_total{device!~\"lo|bond[0-9]|cbr[0-9]|veth.*|br-.*|docker.*|flannel.*|cni.*\"}[5m]) * 8 < 0",
     "legendFormat": "{{device}} (out)"
    }
   ]
  },
  {
   "title": "Traffic (1d)",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device!~\"lo|bond[0-9]|cbr[0-9]|veth.*|br-.*|docker.*|flannel.*|cni.*\"}[24h])) by (device)",
     "legendFormat": "{{ device }}"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device!~\"lo|bond[0-9]|cbr[0-9]|veth.*|br-.*|docker.*|flannel.*|cni.*\"}[24h])) by (device)",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Traffic (7d)",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device!~\"lo|bond[0-9]|cbr[0-9]|veth.*|br-.*|docker.*|flannel.*|cni.*\"}[7d])) by (device)",
     "legendFormat": "{{ device }}"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device!~\"lo|bond[0-9]|cbr[0-9]|veth.*|br-.*|docker.*|flannel.*|cni.*\"}[7d])) by (device)",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Disk Size",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=~\"/dev/.*\"}"
    }
   ]
  },
  {
   "title": "Disk Usage History",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=~\"/dev/.*\"} - node_filesystem_avail_bytes{device=~\"/dev/.*\"}",
     "legendFormat": "{{mountpoint}} (used)"
    },
    {
     "expr": "node_filesystem_avail_bytes{device=~\"/dev/.*\"}",
     "legendFormat": "{{mountpoint}} (free)"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{device=~\"/dev/.*\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total[5m])",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(node_disk_writes_completed_total[5m])",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{device=~\"/dev/.*\"}) - sum(node_filesystem_free_bytes{device=~\"/dev/.*\"})",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{device=~\"/dev/.*\"})",
     "legendFormat": "total"
    }
   ]
  }
 ]
}