{
 "title": "Nodes / node_exporter Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_time_seconds,node)"
    }
   },
   { "name": "public_device", "query": "enp0s3|ens\\d" }
  ]
 },
 "panels": [
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (cpu) (node_cpu_seconds_total{node=~\"$node\", mode=\"idle\"}))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(sum by (cpu) (irate(node_cpu_seconds_total{node=~\"$node\", mode!=\"idle\"}[5m])))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (mode) (irate(node_cpu_seconds_total{node=~\"$node\", mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "count(sum by (cpu) (node_cpu_seconds_total{node=~\"$node\", mode=\"idle\"}))",
     "legendFormat": "cpu count"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"$node\"} - node_memory_MemFree_bytes{node=~\"$node\"} - node_memory_Cached_bytes{node=~\"$node\"} - node_memory_Buffers_bytes{node=~\"$node\"} - node_memory_Slab_bytes{node=~\"$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{node=~\"$node\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{node=~\"$node\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_Slab_bytes{node=~\"$node\"}",
     "legendFormat": "Slab"
    },
    {
     "expr": "node_memory_MemFree_bytes{node=~\"$node\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"$node\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"$node\"} - node_memory_MemAvailable_bytes{node=~\"$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"$node\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{node=~\"$node\"} - node_memory_SwapCached_bytes{node=~\"$node\"} - node_memory_SwapFree_bytes{node=~\"$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_SwapCached_bytes{node=~\"$node\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_SwapFree_bytes{node=~\"$node\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{node=~\"$node\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Swap Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{node=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Traffic In (7d)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{node=~\"$node\", device=~\"$public_device\"}[7d])) by (device)"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{node=~\"$node\", device=~\"/dev/.*\"}) - sum(node_filesystem_free_bytes{node=~\"$node\", device=~\"/dev/.*\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{node=~\"$node\", device=~\"/dev/.*\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed_total{node=\"$node\"}[5m]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(rate(node_disk_writes_completed_total{node=\"$node\"}[5m]))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{node=~\"$node\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*|br-.*|docker.*|flannel.*|cni.*\"}[5m]) * 8 > 0",
     "legendFormat": "{{device}} (in)"
    },
    {
     "expr": "-irate(node_network_transmit_bytes_total{node=~\"$node\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*|br-.*|docker.*|flannel.*|cni.*\"}[5m]) * 8 < 0",
     "legendFormat": "{{device}} (out)"
    }
   ]
  },
  {
   "title": "Traffic (30d)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (device) (increase(node_network_receive_bytes_total{node=~\"$node\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*|br-.*|docker.*|flannel.*|cni.*\"}[30d]))",
     "legendFormat": "{{ device }}"
    },
    {
     "expr": "sum by (device) (increase(node_network_transmit_bytes_total{node=~\"$node\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*|br-.*|docker.*|flannel.*|cni.*\"}[30d]))",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Traffic Out (7d)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{node=~\"$node\", device=~\"$public_device\"}[7d])) by (device)"
    }
   ]
  }
 ]
}