{
 "title": "Resources / S3",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Bucket Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(s3_objects_size_sum_bytes[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Object Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(s3_objects[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bucket Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "last_over_time(s3_objects_size_sum_bytes[1h])",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "Object Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "last_over_time(s3_objects[1h])", "legendFormat": "{{ bucket }}" }
   ]
  },
  {
   "title": "Last Modified",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "last_over_time(s3_last_modified_object_date[1h]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}