{
 "title": "Services / traQ",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prom", "query": "prometheus" },
   {
    "name": "logs_datasource",
    "query": "victoriametrics-logs-datasource"
   },
   { "name": "filter" },
   {
    "name": "url",
    "query": {
     "query": "label_values(echo_request_duration_seconds_count, url)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"traq\"}"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds"
    }
   ]
  },
  {
   "title": "Online Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(traq_online_users)" }
   ]
  },
  {
   "title": "WS Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(traq_ws_connections)" }
   ]
  },
  {
   "title": "Public Channels",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "traq_channels_count_total" }
   ]
  },
  {
   "title": "Online Users",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "traq_online_users", "legendFormat": "{{ user_type }}" }
   ]
  },
  {
   "title": "WS Connections",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "traq_ws_connections", "legendFormat": "{{ user_type }}" }
   ]
  },
  {
   "title": "Public Channels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "traq_channels_count_total", "legendFormat": "channels" }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Total Messages",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "traq_messages_count_total" }
   ]
  },
  {
   "title": "Total Messages",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "traq_messages_count_total", "legendFormat": "messages" }
   ]
  },
  {
   "title": "Messages per hour",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(traq_messages_count_total[1h])",
     "legendFormat": "increase"
    }
   ]
  },
  { "title": "WebRTC (Qall)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Active WebRTC Channels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "traq_webrtc_using_channels", "legendFormat": "channels" }
   ]
  },
  {
   "title": "Active WebRTC Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "traq_webrtc_using_users", "legendFormat": "users" }
   ]
  },
  { "title": "Misc.", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "HTTP Request Rate (1h)",
   "type": "stat",
   "description": "Rateof HTTP request in the last 1 hour",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(traq_http_requests_total[1h]))"
    }
   ]
  },
  {
   "title": "HTTP Error Rate (1h)",
   "type": "stat",
   "description": "HTTP request error (4xx, 5xx) rate in the last 1 hour",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(echo_request_duration_seconds_count{code=~\"[45]..\"}[1h])) / sum(increase(echo_request_duration_seconds_count[1h]))",
     "legendFormat": "error %"
    }
   ]
  },
  {
   "title": "Bot Event Error Rate (1h)",
   "type": "stat",
   "description": "Bot event error rate in the last 1 hour",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traq_bot_event_send_count_total{status!=\"ok\"}[1h])) / sum(increase(traq_bot_event_send_count_total[1h]))",
     "legendFormat": "error %"
    }
   ]
  },
  {
   "title": "FCM Error Rate (1h)",
   "type": "stat",
   "description": "FCM message error rate in the last 1 hour",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(firebase_fcm_send_count_total{result!=\"ok\"}[1h])) / sum(increase(firebase_fcm_send_count_total[1h]))",
     "legendFormat": "error %"
    }
   ]
  },
  {
   "title": "FCM Avg Msgs / Batch (1h)",
   "type": "stat",
   "description": "Average number of messages per batch FCM request in the last 1 hour",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(firebase_fcm_send_count_total[1h])) / sum(increase(firebase_fcm_batch_request_count_total[1h]))",
     "legendFormat": "msgs / batch"
    }
   ]
  },
  {
   "title": "CPU Time (1h)",
   "type": "stat",
   "description": "User/System CPU time in the last 1h",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(process_cpu_seconds_total[1h])",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "HTTP Requests (1h)",
   "type": "timeseries",
   "description": "Number of HTTP requests over the last 1 hour from any point in time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(echo_request_duration_seconds_count{code=~\"1..\"}[1h]))",
     "legendFormat": "100s"
    },
    {
     "expr": "sum(increase(echo_request_duration_seconds_count{code=~\"2..\"}[1h]))",
     "legendFormat": "200s"
    },
    {
     "expr": "sum(increase(echo_request_duration_seconds_count{code=~\"3..\"}[1h]))",
     "legendFormat": "300s"
    },
    {
     "expr": "sum(increase(echo_request_duration_seconds_count{code=~\"4..\"}[1h]))",
     "legendFormat": "400s"
    },
    {
     "expr": "sum(increase(echo_request_duration_seconds_count{code=~\"5..\"}[1h]))",
     "legendFormat": "500s"
    },
    {
     "expr": "sum(increase(echo_request_duration_seconds_count{code!~\"[12345]..\"}[1h]))",
     "legendFormat": "unknown"
    }
   ]
  },
  {
   "title": "HTTP Requests (1h)",
   "type": "timeseries",
   "description": "Number of HTTP requests over the last 1 hour from any point in time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (method) (increase(echo_request_duration_seconds_count[1h]))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "FCM Batch Requests (1h)",
   "type": "timeseries",
   "description": "Number of FCM batch requests over the last 1 hour from any point in time",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(firebase_fcm_batch_request_count_total[1h])",
     "legendFormat": "{{ result }}"
    }
   ]
  },
  {
   "title": "FCM Send Counts (1h)",
   "type": "timeseries",
   "description": "Number of FCM messages sent in the last 1 hour from any point in time. Differs from the actual request count (see batch requests).",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(firebase_fcm_send_count_total[1h])",
     "legendFormat": "{{ result }}"
    }
   ]
  },
  {
   "title": "Bot Event Send Counts (1h)",
   "type": "timeseries",
   "description": "Number of bot events sent in the last 1 hour from any point in time",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (status) (increase(traq_bot_event_send_count_total[1h]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  { "title": "API Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Request Counts (1h)",
   "type": "timeseries",
   "description": "Top 10 endpoints with the most number of HTTP requests over the last 1 hour from any point in time",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum by (method, url, code) (increase(echo_request_duration_seconds_count[1h])))",
     "legendFormat": "{{method}} ({{ code }}) {{ url }}"
    }
   ]
  },
  {
   "title": "Total Response Time (1h)",
   "type": "timeseries",
   "description": "Top 10 endpoints with the most total response time over the last 1 hour from any point in time. Excludes `/api/v3/ws` and `/api/v3/bots/ws`. May not match the actual CPU time due to request coalescing etc.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, sum by (method, url, code) (increase(echo_request_duration_seconds_sum{url!=\"/api/v3/ws\",url!=\"/api/v3/bots/ws\"}[1h])))",
     "legendFormat": "{{method}} ({{ code }}) {{ url }}"
    }
   ]
  },
  {
   "title": "Avg Latency (1h)",
   "type": "timeseries",
   "description": "Top 10 end points with the longest average latency over the last 1 hour from any point in time. Excludes `/api/v3/ws` and `/api/v3/bots/ws`. Calculated by `(total response time) / (request counts)`.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10,\n  rate(echo_request_duration_seconds_sum{url!=\"/api/v3/ws\",url!=\"/api/v3/bots/ws\"}[1h])\n    / rate(echo_request_duration_seconds_count{url!=\"/api/v3/ws\",url!=\"/api/v3/bots/ws\"}[1h])\n)",
     "legendFormat": "{{method}} ({{ code }}) {{ url }}"
    }
   ]
  },
  {
   "title": "API Latency Heatmap by Path",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency Heatmap ($url)",
     "type": "heatmap",
     "description": "Number of requests over the last 1 hour from any point in time",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 115 },
     "repeat": "url",
     "targets": [
      {
       "expr": "sum by (le) (increase(echo_request_duration_seconds_bucket{url=\"$url\"}[1h]))",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  },
  {
   "title": "API Status Code by Path",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests by Code ($url)",
     "type": "timeseries",
     "description": "Number of HTTP requests over the last 1 hour from any point in time",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 116 },
     "repeat": "url",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(echo_request_duration_seconds_count{code=~\"1..\",url=~\"$url\"}[1h]))",
       "legendFormat": "100s"
      },
      {
       "expr": "sum(increase(echo_request_duration_seconds_count{code=~\"2..\",url=~\"$url\"}[1h]))",
       "legendFormat": "200s"
      },
      {
       "expr": "sum(increase(echo_request_duration_seconds_count{code=~\"3..\",url=~\"$url\"}[1h]))",
       "legendFormat": "300s"
      },
      {
       "expr": "sum(increase(echo_request_duration_seconds_count{code=~\"4..\",url=~\"$url\"}[1h]))",
       "legendFormat": "400s"
      },
      {
       "expr": "sum(increase(echo_request_duration_seconds_count{code=~\"5..\",url=~\"$url\"}[1h]))",
       "legendFormat": "500s"
      },
      {
       "expr": "sum(increase(echo_request_duration_seconds_count{instance=\"$server\",code!~\"[12345]..\",url=~\"$url\"}[1h]))",
       "legendFormat": "unknown"
      }
     ]
    }
   ]
  },
  {
   "title": "API Response Size by Path",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response Size ($url)",
     "type": "heatmap",
     "description": "Response size heatmap over the last 1 hour from any point in time",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 117 },
     "repeat": "url",
     "targets": [
      {
       "expr": "sum by (le) (increase(echo_response_size_bytes_bucket{url=\"$url\"}[1h]))",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  },
  { "title": "Go Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 102 },
   "options": {
    "content": "Goのmemstatsの項目をみてみる - 雑なメモ書き  \nhttps://hiroyukim.hatenablog.com/entry/2019/02/28/130907"
   }
  },
  {
   "title": "Memory in Off-Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_mspan_inuse_bytes", "legendFormat": "MSpanInuse" },
    { "expr": "go_memstats_mspan_sys_bytes", "legendFormat": "MSpanSys" },
    { "expr": "go_memstats_mcache_inuse_bytes", "legendFormat": "MCacheInuse" },
    { "expr": "go_memstats_mcache_sys_bytes", "legendFormat": "MCacheSys" },
    {
     "expr": "go_memstats_buck_hash_sys_bytes",
     "legendFormat": "BuckHashSys"
    },
    { "expr": "go_memstats_gc_sys_bytes", "legendFormat": "GCSys" },
    { "expr": "go_memstats_next_gc_bytes", "legendFormat": "NextGC" }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_heap_alloc_bytes", "legendFormat": "HeapAlloc" },
    { "expr": "go_memstats_heap_idle_bytes", "legendFormat": "HeapIdle" },
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "HeapInuse" },
    { "expr": "go_memstats_heap_sys_bytes", "legendFormat": "HeapSys" },
    {
     "expr": "go_memstats_heap_released_bytes",
     "legendFormat": "HeapReleased"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_stack_inuse_bytes", "legendFormat": "StackInuse" },
    { "expr": "go_memstats_stack_sys_bytes", "legendFormat": "StackSys" }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_sys_bytes", "legendFormat": "Sys" }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "description": "`mallocs_total - frees_total`",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total - go_memstats_frees_total",
     "legendFormat": "Mallocs"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated (1h)",
   "type": "timeseries",
   "description": "How many heap objects are allocated (rate over 1h)",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "obj/sec" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total[1h])",
     "legendFormat": "Allocation Rate"
    }
   ]
  },
  {
   "title": "Rates of Allocation (1h)",
   "type": "timeseries",
   "description": "Number of bytes allocated per second (rate over 1h)",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total[1h])",
     "legendFormat": "Allocation Rate"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "go_gc_duration_seconds", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "goroutines" }
   ]
  }
 ]
}