{
 "title": "Services / SwitchBot",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "device",
    "query": {
     "query": "label_values(switchbot_temperature, device_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switchbot_temperature{device_name=~\"$device\"}",
     "legendFormat": "{{ device_name }}"
    }
   ]
  },
  {
   "title": "Absolute Humidity (g/m^3)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "congm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(switchbot_humidity{device_name=~\"$device\"} / 100) * (2.718 ^ (20.386 - (5132 / (switchbot_temperature{device_name=~\"$device\"} + 273.15)))) * 133.32 / 8.314 / (switchbot_temperature{device_name=~\"$device\"} + 273.15) * 18.01528",
     "legendFormat": "{{ device_name }}"
    }
   ]
  },
  {
   "title": "Discomfort Index",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "0.81 * switchbot_temperature{device_name=~\"$device\"} + 0.01 * switchbot_humidity{device_name=~\"$device\"} * (0.99 * switchbot_temperature{device_name=~\"$device\"} - 14.3) + 46.3",
     "legendFormat": "{{ device_name }}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by (device_name) (switchbot_temperature{device_name=~\"$device\"})",
     "legendFormat": "{{ device_name }}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "avg by (device_name) (switchbot_humidity{device_name=~\"$device\"})",
     "legendFormat": "{{ device_name }}"
    }
   ]
  },
  {
   "title": "Discomfort Index",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (device_name) (\r\n0.81 * switchbot_temperature{device_name=~\"$device\"} + 0.01 * switchbot_humidity{device_name=~\"$device\"} * (0.99 * switchbot_temperature{device_name=~\"$device\"} - 14.3) + 46.3\r\n)",
     "legendFormat": "{{ device_name }}"
    }
   ]
  },
  {
   "title": "Absolute Humidity (hPa)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "expr": "avg by (device_name) (\r\n(switchbot_humidity{device_name=~\"$device\"} / 100) * (2.718 ^ (20.386 - (5132 / (switchbot_temperature{device_name=~\"$device\"} + 273.15)))) * 133.32 / 100\r\n)",
     "legendFormat": "{{ device_name }}"
    }
   ]
  },
  {
   "title": "Absolute Humidity (g/m^3)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "congm3" } },
   "targets": [
    {
     "expr": "avg by (device_name) (\r\n(switchbot_humidity{device_name=~\"$device\"} / 100) * (2.718 ^ (20.386 - (5132 / (switchbot_temperature{device_name=~\"$device\"} + 273.15)))) * 133.32 / 8.314 / (switchbot_temperature{device_name=~\"$device\"} + 273.15) * 18.01528\r\n)",
     "legendFormat": "{{ device_name }}"
    }
   ]
  }
 ]
}