apiVersion: v1
kind: Secret
metadata:
    name: s3-exporter
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    access-key: ENC[AES256_GCM,data:4ewF6jBOC0hR8o+63foWAkvwt2Q=,iv:hG5J7ZKZZgzwTyW4Iqtiy/WuuWG2hU67jNaW9l8e1dQ=,tag:el/MBEJJJup7OkVp3HDKlA==,type:str]
    secret-key: ENC[AES256_GCM,data:nuMV4blJN/bXw7NpxHUSjPRzBvh0GO6QSuLK/SP+FQCvFv80D2Mxjw==,iv:Gy1yhoQ/TynDhwPR8hILDtI9MpqKeD6TYJtDA9U0QNc=,tag:W+umqY7gc/5ummL+VdSlFg==,type:str]
    endpoint: ENC[AES256_GCM,data:iHqXcCftWsD4NtxJPXS94g+QxW2QabO4izCt545c/vkyYfCTOjcg,iv:PEiOXVDg02jDMWUj8LnSsUBjOpCuwGkv9l3XPoJlfB8=,tag:uHFOgKThynLgTNKXv5qQHA==,type:str]
    region: ENC[AES256_GCM,data:Gbo840yp2FrKoqSCCtA=,iv:u4vOfi0KGbb0zvJ9O2RvZJLvkRSPCg55zyNsRcmEMG8=,tag:rpDXXxkDf9iGLuGptXIpmg==,type:str]
sops:
    age:
        - recipient: age1g2rwkffct3veu3zl5a09cny4qgjw5he9drdxjwxqclzq6fa0ldtql4kxvd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIM3NWVlJuYm9IYjRoVWND
            R2RjMk85YUFrdFBNVU1oZVlHL2ExdTBiYWhzCjZ0RlhZSVAzYzUreWt0Z1BOM0Vq
            aThzUmJMdVExbXFvVXk2NXQ1YWJNTFkKLS0tIDYydFg2cDVnak5SMUhLejM4Zklh
            a2pTbkovVGtvcWtieHoxa21ETk0wVlUKamM3G60wcWXQVEJxMfrWOja8uxqWVlKE
            eOlHFP3J3LCnHbzsUJrrxapvgz1GPlxEs7vwocWsmb+6SBDl7XC2Dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-06T14:24:56Z"
    mac: ENC[AES256_GCM,data:nw6bPCpeeW8YYqpvK6Vb2bdlZV1HOZEXfm7ArqqmyCgOtu+hMnNsM4NK2NgcG/pf5YPdxYEzwRaMVRvQNILODkwlQOy0IQG2f+CF6cOB8IxvZvXJa9wBGYw0Hj1HGpUyKAh+WfnepImDRQ2w+0ruSE7HtFDheeLaqrd4wVt8V6k=,iv:OGWqHtH2Z4DefbUc01BhF4waiKty5z5SOm/xlcnkUM0=,tag:Bb74n6X/WMmByxvdmEnHXQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.7.3
