apiVersion: v1
kind: Secret
metadata:
    name: traq
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    mariadb-password: ENC[AES256_GCM,data:1i3W43ZnjzrkZsFpRMs3t9RqETYE+w==,iv:RWc9l4Ucadq2ZKmn3rbBvELKv3lHfWi8i4MrCtAz/6I=,tag:dJW1B3fdnKAF89+Y5/G6RA==,type:str]
    skyway-secret: ENC[AES256_GCM,data:Hhp2Qi8XPgnObdGQb76d+hGbmD24Jj8T3naRtkYrVCY=,iv:zKBEeEmdISTJ98tRCdLsuGDVy3CmnDE/nTqebOnGyPI=,tag:vzcIq3mKByE0ZPxuMpDU5g==,type:str]
    s3-access-key: ENC[AES256_GCM,data:a9pOLVw27vWAjAefFcqCx2w1YTc=,iv:9JbdAhJ0ifT6I2XZ9nfYlsoPVMgHOpH2GCQXy8YRyXA=,tag:UGk3QyFeCoU+Tz/czOZoZA==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:/rYm1HdMqhwjeq1HfMcZnPmNBUo25uSRS562E0EyjPd7fVuhTlfJrA==,iv:9MIujtofM7gQz5cNfO6GKURpt4W8BSDULp9acdEf+rg=,tag:TI1aLZCGIQq4eZ9auCX+lg==,type:str]
    es-password: ENC[AES256_GCM,data:TPaQ13MYQYAtvRmxeE2I6kprOPkI3o6lr3m3npeHsS8=,iv:FwEjRWtMSziWwjNvC4YNqyZF/lybNE02rzjiad8Wpss=,tag:dECcpyxAm5/GVV0u33C1xA==,type:str]
sops:
    age:
        - recipient: age1g2rwkffct3veu3zl5a09cny4qgjw5he9drdxjwxqclzq6fa0ldtql4kxvd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZXBKT09HdGNncUFIbldT
            RURMQk03TFhGbS8zeWplcWRFSk9aVloxZWo0CjlISmM0TnRiUUpWNmVZczZuK3hE
            a1k2UVBIdHhnOFg5WXR0TWN3b2lNd0UKLS0tIGhqL251blFjQllYZ2FoM3lvNm9K
            S0x2TS9yTU56N0NmTlYydVN6L012K00KzODLQGA316ejNJfIFvq39SpJKuIJhSUy
            tSHO5BfQ/dr/vlCyXYegPY6earrWOBXHjIQdWrv2ZeDBaDKFEPrtFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-06T14:11:57Z"
    mac: ENC[AES256_GCM,data:jBWxik/Vkyobl0Li+85441hNVUhTrG4IdXf8CksJgoQxx0/nKH98b3S5zsLhahhgwvg25v4meSX03OfzmFBY//4Qu/F5BijwDfZ5VyK2e7IHUy6oUJOHtupsqs/oXfNL0ERYL0U5ZqIjN0rt1i+cMWtszUwDcsR5WxJNvrEnP90=,iv:6zyfrENUTaxc0hMfxpv73mNiWUBKkG5un4PCXNR0uQ4=,tag:wuyXbTkxRW+S6KxSgnWvPw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
