helmCharts:
  - repo: oci://ghcr.io/motoki317/charts
    name: kd
    version: "0.3.3"
    includeCRDs: true
    namespace: kd
    releaseName: kd
    valuesFile: values.yaml

resources:
  - certificate.yaml
