apiVersion: v1
kind: Secret
metadata:
    name: storage
stringData:
    REGISTRY_STORAGE_S3_ACCESSKEY: ENC[AES256_GCM,data:1LFQKMuSz5Fs0p/fUbnsmI+zYmI=,iv:IVd8Gd0KvbtyinNBx7c6Tv/7lWMv08VSaBQ2K6l09qQ=,tag:hK2bcmYNENjRKjXJyUSQpg==,type:str]
    REGISTRY_STORAGE_S3_SECRETKEY: ENC[AES256_GCM,data:Enp1P9UiU8ajkYpR2qvg/qW+e3HXOCke74p6mL1kHi/0pxPwvnj5ZA==,iv:7w1XyzvCaAAWu3BWRStuYJFlfZfRy0Mw2kaPay/1zdQ=,tag:D8Dc9E4O1fKtfjmt7si2bQ==,type:str]
sops:
    age:
        - recipient: age1g2rwkffct3veu3zl5a09cny4qgjw5he9drdxjwxqclzq6fa0ldtql4kxvd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TS8vc0VjWG5xQVB3NUtl
            OGQ0dzhpalpQYWVPY2lhYWdMYzZNL2RRVkNBCjlmOUFDU1l4Q2Q5TnV0TjlqTG1P
            WExGVEI1bDZvd0ZrODd5Nlo3UE9UN0UKLS0tIHBZT05aRmltTkFnUFVWNmxKS3h6
            NThJK2VRRTcvZVVNT2VmNXd3WlhHdGsKRRxKo+LjVR0BK72Ugth+aHrFA4q7km+q
            FYwSrKM5apWokWktV2xfeA0mRH/R/WYa826CY4GYihxAnuAEuq1JzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-06T13:49:51Z"
    mac: ENC[AES256_GCM,data:rZDF22bJWI67H1LKFczm7abhCW47u2gVjD4UA6I0V2J3gg8PX4uH85H5LjsyXKYyRALOG3RlEprzePwknhgsclhEHs1tz4bFxdIYlWdKMdkQl27ZijThmgxpHiVw1uRIuucddW3dASOM7wGkv1ezZn/wrMVhLrKN1/FIacqBSDA=,iv:K08Sk+IzRj4/dgy5C0xR6vckrRRPvCz0+V6Rth8dXZA=,tag:P2Cj/IuOsHENoVXyi9T+2w==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.7.3
