{
 "title": "Cluster / Containers",
 "tags": [
  "cAdvisor",
  "cluster-mixin"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "group_by",
    "query": "namespace : namespace, pod : namespace\\, pod, container : namespace\\, pod\\, container"
   },
   {
    "name": "legend",
    "query": "{{ namespace }}/{{ pod }}/{{ container }}"
   },
   {
    "name": "hostname",
    "query": {
     "query": "label_values(kube_node_labels,node)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_last_seen, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_last_seen{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_last_seen{namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Running pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (pod) (container_last_seen{node=~\"$hostname\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}))"
    }
   ]
  },
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{node=~\"$hostname\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{node=~\"$hostname\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", image!=\"\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Virtual Memory Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{node=~\"$hostname\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", image!=\"\"})"
    }
   ]
  },
  {
   "title": "Physical Memory Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{node=~\"$hostname\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", image!=\"\"})"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_swap{node=~\"$hostname\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})"
    }
   ]
  },
  {
   "title": "Running Pods by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (namespace) (count by (pod, namespace) (container_last_seen{node=~\"$hostname\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by ($group_by) ((container_last_seen{node=~\"$hostname\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}))",
     "legendFormat": "$legend"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 17, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - avg by (namespace, pod, node) (container_start_time_seconds{node=~\"$hostname\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "$legend"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by ($group_by) (rate(container_cpu_usage_seconds_total{node=~\"$hostname\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", image!=\"\"}[$__rate_interval]))",
     "legendFormat": "$legend"
    }
   ]
  },
  {
   "title": "Virtual Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by ($group_by) (container_memory_usage_bytes{node=~\"$hostname\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", image!=\"\"})",
     "legendFormat": "$legend"
    }
   ]
  },
  {
   "title": "Memory Working Set Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by ($group_by) (container_memory_working_set_bytes{node=~\"$hostname\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", image!=\"\"})",
     "legendFormat": "$legend"
    }
   ]
  },
  {
   "title": "Physical Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by ($group_by) (container_memory_rss{node=~\"$hostname\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", image!=\"\"})",
     "legendFormat": "$legend"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by ($group_by) (container_memory_swap{node=~\"$hostname\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", image!=\"\"})",
     "legendFormat": "$legend"
    }
   ]
  },
  {
   "title": "Minor Page Faults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "targets": [
    {
     "expr": "sum by ($group_by) (rate(container_memory_failures_total{node=~\"$hostname\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", scope=\"container\", failure_type=\"pgfault\", image!=\"\"}[$__rate_interval]))",
     "legendFormat": "$legend"
    }
   ]
  },
  {
   "title": "Major Page Faults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "targets": [
    {
     "expr": "sum by ($group_by) (rate(container_memory_failures_total{node=~\"$hostname\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", scope=\"container\", failure_type=\"pgmajfault\", image!=\"\"}[$__rate_interval]))",
     "legendFormat": "$legend"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by ($group_by) (rate(container_network_receive_bytes_total{node=~\"$hostname\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) * 8)",
     "legendFormat": "{{ namespace }}/{{ pod }}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by ($group_by) (rate(container_network_transmit_bytes_total{node=~\"$hostname\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) * 8)",
     "legendFormat": "{{ namespace}}/{{ pod }}"
    }
   ]
  },
  {
   "title": "Network Rx (Packet Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by ($group_by) (rate(container_network_receive_packets_total{node=~\"$hostname\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{ namespace }}/{{ pod }}"
    }
   ]
  },
  {
   "title": "Network Tx (Packet Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by ($group_by) (rate(container_network_transmit_packets_total{node=~\"$hostname\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{ namespace }}/{{ pod }}"
    }
   ]
  },
  {
   "title": "Network Rx (Packet Dropped)",
   "type": "timeseries",
   "description": "No data is usually a good thing here",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by ($group_by) (rate(container_network_receive_packets_dropped_total{node=~\"$hostname\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) > 0",
     "legendFormat": "{{ namespace }}/{{ pod }}"
    }
   ]
  },
  {
   "title": "Network Tx (Packet Dropped)",
   "type": "timeseries",
   "description": "No data is usually a good thing here",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by ($group_by) (rate(container_network_transmit_packets_dropped_total{node=~\"$hostname\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) > 0",
     "legendFormat": "{{ namespace }}/{{ pod }}"
    }
   ]
  },
  {
   "title": "Network Rx (Errors)",
   "type": "timeseries",
   "description": "No data is usually a good thing here",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by ($group_by) (rate(container_network_receive_errors_total{node=~\"$hostname\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) > 0",
     "legendFormat": "{{ namespace }}/{{ pod }}"
    }
   ]
  },
  {
   "title": "Network Tx (Errors)",
   "type": "timeseries",
   "description": "No data is usually a good thing here",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by ($group_by) (rate(container_network_transmit_errors_total{node=~\"$hostname\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) > 0",
     "legendFormat": "{{ namespace }}/{{ pod }}"
    }
   ]
  }
 ]
}