{
 "title": "Cluster / HPA",
 "tags": [ "cluster-mixin" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_horizontalpodautoscaler_status_current_replicas,namespace)"
    }
   },
   {
    "name": "hpa",
    "query": {
     "query": "label_values(kube_horizontalpodautoscaler_status_current_replicas{namespace=~\"$namespace\"},horizontalpodautoscaler)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by (namespace, horizontalpodautoscaler) (kube_horizontalpodautoscaler_status_current_replicas{namespace=~\"$namespace\", horizontalpodautoscaler=~\"$hpa\"})",
     "legendFormat": "{{ namespace }}/{{ horizontalpodautoscaler }} (current)"
    },
    {
     "expr": "avg by (namespace, horizontalpodautoscaler) (kube_horizontalpodautoscaler_status_desired_replicas{namespace=~\"$namespace\", horizontalpodautoscaler=~\"$hpa\"})",
     "legendFormat": "{{ namespace }}/{{ horizontalpodautoscaler }} (desired)"
    }
   ]
  },
  {
   "title": "CPU Average (Actual Value)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (namespace, horizontalpodautoscaler) (kube_horizontalpodautoscaler_status_target_metric{namespace=~\"$namespace\", horizontalpodautoscaler=~\"$hpa\", metric_name=\"cpu\", metric_target_type=\"average\"})",
     "legendFormat": "{{ namespace }}/{{ horizontalpodautoscaler }}"
    }
   ]
  },
  {
   "title": "HPA CPU Utilization Target",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (namespace, horizontalpodautoscaler) (kube_horizontalpodautoscaler_status_target_metric{namespace=~\"$namespace\", horizontalpodautoscaler=~\"$hpa\", metric_name=\"cpu\", metric_target_type=\"utilization\"})",
     "legendFormat": "{{ namespace }}/{{ horizontalpodautoscaler }}"
    }
   ]
  }
 ]
}