{
 "title": "Cluster / Main",
 "tags": [ "cluster-mixin" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (instance) (sum by (instance, cpu) (irate(node_cpu_seconds_total{mode!~\"idle|steal\"}[5m])))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg by (instance) (sum by (instance, core) (rate(windows_cpu_time_total{mode!=\"idle\"}[5m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load Average (load5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "node_load5", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Instance Uptime",
   "type": "table",
   "gridPos": { "h": 24, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "1 - (sum by (instance) (node_memory_free_bytes + node_memory_inactive_bytes)) / (sum by (instance) (node_memory_total_bytes))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "(windows_cs_physical_memory_bytes - windows_os_physical_memory_free_bytes) / windows_cs_physical_memory_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes - node_memory_SwapCached_bytes - node_memory_SwapFree_bytes) / node_memory_SwapTotal_bytes",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (instance, device) (1 - (node_filesystem_avail_bytes{device=~\"/dev/.*\"} / node_filesystem_size_bytes{device=~\"/dev/.*\"}))",
     "legendFormat": "{{instance}} {{device}}"
    },
    {
     "expr": "avg by (nodinstancee, device) (1 - (windows_logical_disk_free_bytes{volume!~\"Harddisk.+\"} / windows_logical_disk_size_bytess{volume!~\"Harddisk.+\"}))",
     "legendFormat": "{{instance}} {{volume}}"
    }
   ]
  },
  {
   "title": "Major Page Faults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "targets": [
    {
     "expr": "rate(node_vmstat_pgmajfault[5m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "rate(windows_memory_swap_page_reads_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_network_receive_bytes_total{device!~\"lo|bond[0-9]|cbr[0-9]|veth.*|br-.*|docker.*|flannel.*|cni.*\"}[5m])) * 8",
     "legendFormat": "{{ instance }} (in)"
    },
    {
     "expr": "-sum by (instance) (irate(node_network_transmit_bytes_total{device!~\"lo|bond[0-9]|cbr[0-9]|veth.*|br-.*|docker.*|flannel.*|cni.*\"}[5m])) * 8",
     "legendFormat": "{{ instance }} (out)"
    }
   ]
  }
 ]
}