{
 "title": "Cluster / Nodes Overview",
 "tags": [ "cluster-mixin" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "opencost_ds", "query": "prometheus" },
   {
    "name": "nodepool",
    "query": {
     "query": "label_values(kube_node_labels,label_karpenter_sh_nodepool)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "query_result(kube_node_labels{label_karpenter_sh_nodepool=~\"$nodepool\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (label_karpenter_sh_nodepool) (kube_node_labels{node=~\"$node\", node!~\"^fargate-.*\", label_karpenter_sh_nodepool=~\"$nodepool\"})",
     "legendFormat": "{{ label_karpenter_sh_nodepool }}"
    },
    {
     "expr": "count by (label_karpenter_sh_nodepool) (kube_node_labels{node=~\"$node\", node=~\"^fargate-.*\", label_karpenter_sh_nodepool=~\"$nodepool\"})",
     "legendFormat": "Fargate"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "count by (label_karpenter_sh_nodepool) (\n  kube_pod_info{}\n  * on (namespace, pod) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1)\n  * on (node) group_left(label_karpenter_sh_nodepool)\n    kube_node_labels{node=~\"$node\", node!~\"^fargate-.*\", label_karpenter_sh_nodepool=~\"$nodepool\"}\n)",
     "legendFormat": "{{ label_karpenter_sh_nodepool }}"
    },
    {
     "expr": "count by (label_karpenter_sh_nodepool) (\n  kube_pod_info{}\n  * on (namespace, pod) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1)\n  * on (node) group_left(label_karpenter_sh_nodepool)\n    kube_node_labels{node=~\"$node\", node=~\"^fargate-.*\", label_karpenter_sh_nodepool=~\"$nodepool\"}\n)",
     "legendFormat": "Fargate"
    }
   ]
  },
  {
   "title": "Hourly Cost",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (label_karpenter_sh_nodepool) (\r\n  node_total_hourly_cost{}\r\n  * on (node) group_left(label_karpenter_sh_nodepool) (\r\n    avg by (node, label_karpenter_sh_nodepool) (kube_node_labels{node=~\"$node\", node!~\"fargate.*\", label_karpenter_sh_nodepool=~\"$nodepool\"})\r\n  )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n  sum by (node) (container_cpu_allocation{})\n  * avg by (node) (node_cpu_hourly_cost{node=~\"$node\", node=~\"fargate.*\", label_karpenter_sh_nodepool=~\"$nodepool\"})\n)\n+\nsum(\n  sum by (node) (container_memory_allocation_bytes{} / 1024 / 1024 / 1024 + 0.25)\n  * avg by (node) (node_ram_hourly_cost{node=~\"$node\", node=~\"fargate.*\", label_karpenter_sh_nodepool=~\"$nodepool\"})\n)",
     "legendFormat": "Fargate"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "sum(usage) / sum(cores)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n# Normal nodes (node_expoter)\n(sum(rate(\n  node_cpu_seconds_total{mode!~\"idle|iowait|steal\"}\n  * on(instance) group_left()\n    (\n      node_uname_info{}\n      * on(nodename) group_left()\n      label_replace(kube_node_labels{node=~\"$node\", fargate!~\"^fargate-.*\", label_karpenter_sh_nodepool=~\"$nodepool\"}, \"nodename\", \"$1\", \"node\", \"(.*)\")\n    )\n[$__rate_interval])) or vector(0))\n+\n# Fargate nodes (kube cAdvisor)\n(sum(\n  rate(\n    container_cpu_usage_seconds_total{image!=\"\"}\n    * on(node) group_left()\n    kube_node_labels{node=~\"$node\", node=~\"^fargate-.+\", label_karpenter_sh_nodepool=~\"$nodepool\"}\n  [$__rate_interval])\n) or vector(0))\n)\n\n/\n\n(\n# Normal nodes (kubelet)\n(sum(\n  machine_cpu_cores{}\n  * on(node) group_left()\n  kube_node_labels{node=~\"$node\", node!~\"^fargate-.+\", label_karpenter_sh_nodepool=~\"$nodepool\"}\n) or vector(0))\n+\n# Fargate nodes (kube cAdvisor)\n(sum(\n  kube_pod_container_resource_requests{resource=\"cpu\"}\n  * on(node) group_left()\n  kube_node_labels{node=~\"$node\", node=~\"^fargate-.+\", label_karpenter_sh_nodepool=~\"$nodepool\"}\n) or vector(0))\n)",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "timeseries",
   "description": "sum(usage) / sum(ram)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n# Normal nodes (node_exporter)\n(sum(\n  (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)\n  * on(instance) group_left()\n    (\n      node_uname_info{}\n      * on(nodename) group_left()\n      label_replace(kube_node_labels{node=~\"$node\", node!~\"^fargate-.*\", label_karpenter_sh_nodepool=~\"$nodepool\"}, \"nodename\", \"$1\", \"node\", \"(.*)\")\n    )\n) or vector(0))\n+\n# Fargate nodes (kube cAdvisor)\n(sum(\n  container_memory_rss{image!=\"\"}\n  * on(node) group_left()\n  kube_node_labels{node=~\"$node\", node=~\"^fargate-.+\", label_karpenter_sh_nodepool=~\"$nodepool\"}\n) or vector(0))\n)\n\n/\n\n(\n# Normal nodes (kubelet)\n(sum(\n  machine_memory_bytes{}\n  * on(node) group_left()\n  kube_node_labels{node=~\"$node\", node!~\"^fargate-.+\", label_karpenter_sh_nodepool=~\"$nodepool\"}\n) or vector(0))\n+\n# Fargate nodes (kube cAdvisor)\n(sum(\n  kube_pod_container_resource_requests{resource=\"memory\"}\n  * on(node) group_left()\n  kube_node_labels{node=~\"$node\", node=~\"^fargate-.+\", label_karpenter_sh_nodepool=~\"$nodepool\"}\n) or vector(0))\n)",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "CPU Alloc Utilization",
   "type": "timeseries",
   "description": "sum(requests) / sum(allocatable)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{resource=\"cpu\"}\n  * on(namespace, pod) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1)\n  * on(node) group_left()\n  kube_node_labels{node=~\"$node\", label_karpenter_sh_nodepool=~\"$nodepool\"}\n)\n\n/\n\n(\n# Normal nodes (kube-state-metrics)\n(sum(\n  kube_node_status_allocatable{resource=\"cpu\"}\n  * on(node) group_left()\n  kube_node_labels{node=~\"$node\", node!~\"^fargate-.+\", label_karpenter_sh_nodepool=~\"$nodepool\"}\n) or vector(0))\n+\n# Fargate nodes (kube cAdvisor)\n(sum(\n  kube_pod_container_resource_requests{resource=\"cpu\"}\n  * on(node) group_left()\n  kube_node_labels{node=~\"$node\", node=~\"^fargate-.+\", label_karpenter_sh_nodepool=~\"$nodepool\"}\n) or vector(0))\n)",
     "legendFormat": "Alloc Utilization"
    }
   ]
  },
  {
   "title": "Memory Alloc Utilization",
   "type": "timeseries",
   "description": "sum(requests) / sum(allocatable)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (\n  kube_pod_container_resource_requests{resource=\"memory\"}\n  * on(namespace, pod) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1)\n  * on(node) group_left()\n  kube_node_labels{node=~\"$node\", label_karpenter_sh_nodepool=~\"$nodepool\"}\n)\n\n/\n\n(\n# Normal nodes (kube-state-metrics)\n(sum(\n  kube_node_status_allocatable{resource=\"memory\"}\n  * on(node) group_left(node)\n  kube_node_labels{node=~\"$node\", node!~\"^fargate-.+\", label_karpenter_sh_nodepool=~\"$nodepool\"}\n) or vector(0))\n+\n# Fargate nodes (kube cAdvisor)\n(sum(\n  kube_pod_container_resource_requests{resource=\"memory\"}\n  * on(node) group_left(node)\n  kube_node_labels{node=~\"$node\", node=~\"^fargate-.+\", label_karpenter_sh_nodepool=~\"$nodepool\"}\n) or vector(0))\n)",
     "legendFormat": "Alloc Utilization"
    }
   ]
  },
  {
   "title": "Overview (Actual)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "# Normal nodes (node_expoter)\nsum by (label_karpenter_sh_nodepool) (rate(\n  node_cpu_seconds_total{mode!~\"idle|iowait|steal\"}\n  * on(instance) group_left(label_karpenter_sh_nodepool)\n    (\n      node_uname_info{}\n      * on(nodename) group_left(label_karpenter_sh_nodepool)\n      label_replace(kube_node_labels{node=~\"$node\", node!~\"^fargate-.*\", label_karpenter_sh_nodepool=~\"$nodepool\"}, \"nodename\", \"$1\", \"node\", \"(.*)\")\n    )\n[$__rate_interval]))",
       "legendFormat": "{{ label_karpenter_sh_nodepool }}"
      },
      {
       "expr": "# Fargate nodes (kube cAdvisor)\nsum(\n  rate(\n    container_cpu_usage_seconds_total{image!=\"\"}\n    * on(node) group_left()\n    kube_node_labels{node=~\"$node\", node=~\"^fargate-.+\", label_karpenter_sh_nodepool=~\"$nodepool\"}\n  [$__rate_interval])\n)",
       "legendFormat": "Fargate"
      },
      {
       "expr": "# Normal nodes (kubelet)\n(sum(\n  machine_cpu_cores{}\n  * on(node) group_left()\n  kube_node_labels{node=~\"$node\", node!~\"^fargate-.+\", label_karpenter_sh_nodepool=~\"$nodepool\"}\n) or vector(0))\n+\n# Fargate nodes (kube cAdvisor)\n(sum(\n  kube_pod_container_resource_requests{resource=\"cpu\"}\n  * on(node) group_left()\n  kube_node_labels{node=~\"$node\", node=~\"^fargate-.+\", label_karpenter_sh_nodepool=~\"$nodepool\"}\n) or vector(0))",
       "legendFormat": "Total Cores"
      }
     ]
    },
    {
     "title": "RAM Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "# Normal nodes (node_exporter)\nsum by (label_karpenter_sh_nodepool) (\n  (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)\n  * on(instance) group_left(label_karpenter_sh_nodepool)\n    (\n      node_uname_info{}\n      * on(nodename) group_left(label_karpenter_sh_nodepool)\n      label_replace(kube_node_labels{node=~\"$node\", node!~\"^fargate-.*\", label_karpenter_sh_nodepool=~\"$nodepool\"}, \"nodename\", \"$1\", \"node\", \"(.*)\")\n    )\n)",
       "legendFormat": "{{ label_karpenter_sh_nodepool }}"
      },
      {
       "expr": "# Fargate nodes (kube cAdvisor)\nsum by (label_karpenter_sh_nodepool) (\n  container_memory_rss{image!=\"\"}\n  * on(node) group_left()\n  kube_node_labels{node=~\"$node\", node=~\"^fargate-.+\", label_karpenter_sh_nodepool=~\"$nodepool\"}\n)",
       "legendFormat": "Fargate"
      },
      {
       "expr": "# Normal nodes (kubelet)\n(sum(\n  machine_memory_bytes{}\n  * on(node) group_left(node)\n  kube_node_labels{node=~\"$node\", node!~\"^fargate-.+\", label_karpenter_sh_nodepool=~\"$nodepool\"}\n) or vector(0))\n+\n# Fargate nodes (kube cAdvisor)\n(sum(\n  kube_pod_container_resource_requests{resource=\"memory\"}\n  * on(node) group_left(node)\n  kube_node_labels{node=~\"$node\", node=~\"^fargate-.+\", label_karpenter_sh_nodepool=~\"$nodepool\"}\n) or vector(0))",
       "legendFormat": "Total RAM"
      }
     ]
    },
    {
     "title": "CPU Allocation",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (label_karpenter_sh_nodepool) (\n  kube_pod_container_resource_requests{resource=\"cpu\"}\n  * on(node) group_left(label_karpenter_sh_nodepool)\n  kube_node_labels{node=~\"$node\", node!~\"^fargate-.*\", label_karpenter_sh_nodepool=~\"$nodepool\"}\n)",
       "legendFormat": "{{ label_karpenter_sh_nodepool }}"
      },
      {
       "expr": "sum(\n  kube_pod_container_resource_requests{resource=\"cpu\"}\n  * on(node) group_left()\n  kube_node_labels{node=~\"$node\", node=~\"^fargate-.*\", label_karpenter_sh_nodepool=~\"$nodepool\"}\n)",
       "legendFormat": "Fargate"
      },
      {
       "expr": "# Normal nodes (kube-state-metrics)\n(sum(\n  kube_node_status_allocatable{resource=\"cpu\"}\n  * on(node) group_left(node)\n  kube_node_labels{node=~\"$node\", node!~\"^fargate-.+\", label_karpenter_sh_nodepool=~\"$nodepool\"}\n) or vector(0))\n+\n# Fargate nodes (kube cAdvisor)\n(sum(\n  kube_pod_container_resource_requests{resource=\"cpu\"}\n  * on(node) group_left(node)\n  kube_node_labels{node=~\"$node\", node=~\"^fargate-.+\", label_karpenter_sh_nodepool=~\"$nodepool\"}\n) or vector(0))",
       "legendFormat": "Allocatable"
      }
     ]
    },
    {
     "title": "Memory Allocation",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (label_karpenter_sh_nodepool) (\n  kube_pod_container_resource_requests{resource=\"memory\"}\n  * on(node) group_left(label_karpenter_sh_nodepool)\n  kube_node_labels{node=~\"$node\", node!~\"^fargate-.*\", label_karpenter_sh_nodepool=~\"$nodepool\"}\n)",
       "legendFormat": "{{ label_karpenter_sh_nodepool }}"
      },
      {
       "expr": "sum by (label_karpenter_sh_nodepool) (\n  kube_pod_container_resource_requests{resource=\"memory\"}\n  * on(node) group_left()\n  kube_node_labels{node=~\"$node\", node=~\"^fargate-.*\", label_karpenter_sh_nodepool=~\"$nodepool\"}\n)",
       "legendFormat": "Fargate"
      },
      {
       "expr": "# Normal nodes (kube-state-metrics)\n(sum(\n  kube_node_status_allocatable{resource=\"memory\"}\n  * on(node) group_left()\n  kube_node_labels{node=~\"$node\", node!~\"^fargate-.+\", label_karpenter_sh_nodepool=~\"$nodepool\"}\n) or vector(0))\n+\n# Fargate nodes (kube cAdvisor)\n(sum(\n  kube_pod_container_resource_requests{resource=\"memory\"}\n  * on(node) group_left()\n  kube_node_labels{node=~\"$node\", node=~\"^fargate-.+\", label_karpenter_sh_nodepool=~\"$nodepool\"}\n) or vector(0))",
       "legendFormat": "Allocatable"
      }
     ]
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "repeat": "node" },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
   "options": {
    "content": "<h3 style=\"display: flex; height: 100%; justify-content: center; align-items: center;\">\n  <a href=\"/d/k8s_views_nodes/nodes-view?orgId=1&refresh=30s&var-datasource=VictoriaMetrics&var-node=${node}\" target=\"_blank\">\n    To Node Panel\n  </a>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 21 },
   "options": {
    "content": "<div style=\"display: flex; height: 100%; justify-content: center; align-items: center;\">Uptime</div>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_time_seconds - node_boot_time_seconds)\n* on(instance) group_left(nodename)\n  node_uname_info{nodename=~\"$node\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 21 },
   "options": {
    "content": "<div style=\"display: flex; height: 100%; justify-content: center; align-items: center;\">Hourly Cost</div>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_total_hourly_cost{node=~\"$node\", node!~\"fargate.*\"}) or vector(0))\n+\n(sum(container_cpu_allocation{node=~\"$node\", node=~\"fargate.*\"}) * avg(node_cpu_hourly_cost{node=~\"$node\"}) or vector(0))\n+\n(sum(container_memory_allocation_bytes{node=~\"$node\", node=~\"fargate.*\"} / 1024 / 1024 / 1024 + 0.25) * avg(node_ram_hourly_cost{node=~\"$node\"}) or vector(0))"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "kube_node_labels{node=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 23 },
   "options": {
    "content": "<div style=\"display: flex; height: 100%; justify-content: center; align-items: center;\">Pods</div>"
   }
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=~\"$node\"})"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"pods\", node=~\"$node\"})",
     "legendFormat": "max pods"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Pods Capacity",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"pods\", node=~\"$node\"})"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 25 },
   "options": {
    "content": "<div style=\"display: flex; height: 100%; justify-content: center; align-items: center;\">CPU Usage</div>"
   }
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 8, "x": 2, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(\n  node_cpu_seconds_total{mode!~\"idle|iowait|steal\"}\n  * on(instance) group_left(nodename, instance)\n    node_uname_info{nodename=~\"$node\"}\n[$__rate_interval])) or vector(0)\n+\nsum(\n  rate(\n    container_cpu_usage_seconds_total{node=~\"$node\", node=~\"^fargate-.+\", image!=\"\"}\n  [$__rate_interval])\n) or vector(0)",
     "legendFormat": "used"
    },
    {
     "expr": "sum(machine_cpu_cores{node=~\"$node\"})",
     "legendFormat": "cores"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Total CPU",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{node=~\"$node\"})"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 25 },
   "options": {
    "content": "<div style=\"display: flex; height: 100%; justify-content: center; align-items: center;\">RAM Usage</div>"
   }
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 8, "x": 14, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)\n  * on(instance) group_left(nodename)\n    node_uname_info{nodename=~\"$node\"}\n) or vector(0)\n+\nsum(\n  container_memory_rss{node=~\"$node\", node=~\"^fargate-.+\", image!=\"\"}\n) or vector(0)",
     "legendFormat": "used"
    },
    {
     "expr": "machine_memory_bytes{node=~\"$node\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "type": "stat",
   "description": "RAM Total",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_memory_bytes{node=~\"$node\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 27 },
   "options": {
    "content": "<div style=\"display: flex; height: 100%; justify-content: center; align-items: center;\">CPU Requests</div>"
   }
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 8, "x": 2, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  kube_pod_container_resource_requests{resource=\"cpu\", node=~\"$node\"}\r\n  * on(namespace, pod) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1)\r\n)"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", node=~\"$node\"})",
     "legendFormat": "allocatable cpu"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Allocatable",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", node=~\"$node\"})"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 27 },
   "options": {
    "content": "<div style=\"display: flex; height: 100%; justify-content: center; align-items: center;\">RAM Requests</div>"
   }
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 8, "x": 14, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  kube_pod_container_resource_requests{resource=\"memory\", node=~\"$node\"}\r\n  * on(namespace, pod) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1)\r\n)"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", node=~\"$node\"})",
     "legendFormat": "allocatable cpu"
    }
   ]
  },
  {
   "type": "stat",
   "description": "RAM Allocatable",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", node=~\"$node\"})"
    }
   ]
  }
 ]
}