{
 "title": "Cluster / OpenCost",
 "tags": [ "cluster-mixin" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Wide", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Monthly Cluster Cost (Live)",
   "type": "piechart",
   "description": "Cluster cost of last 730h\n\nCluster cost = Node cost + PV cost + Overhead (cluster+LB) cost",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum_over_time(sum_node_total_hourly_cost[730h:1m]) / 60",
     "legendFormat": "workload"
    },
    {
     "expr": "sum(sum_over_time(\n    (\n        sum by (persistentvolume) (pv_hourly_cost)\n        * sum by (persistentvolume) (kube_persistentvolume_capacity_bytes / 1024 / 1024 / 1024)\n    )[730h:1h]\n))",
     "legendFormat": "pv"
    },
    {
     "expr": "sum_over_time(\n    (sum(kubecost_load_balancer_cost OR on() vector(0)) + sum(kubecost_cluster_management_cost))[730h:1h]\n)",
     "legendFormat": "overhead"
    }
   ]
  },
  {
   "title": "Monthly Cluster Cost (Estimation)",
   "type": "piechart",
   "description": "Estimation from the current time range",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time((sum_node_total_hourly_cost)[$__range:$__interval]) / (1h / $__interval) * (730h / $__range)",
     "legendFormat": "workload"
    },
    {
     "expr": "sum_over_time((sum(\n    sum by (persistentvolume) (pv_hourly_cost)\n    * sum by (persistentvolume) (kube_persistentvolume_capacity_bytes / 1024 / 1024 / 1024)\n)[$__range:$__interval])) / (1h / $__interval) * (730h / $__range)",
     "legendFormat": "pv"
    },
    {
     "expr": "sum_over_time((\n  (sum(kubecost_load_balancer_cost OR on() vector(0)) + sum(kubecost_cluster_management_cost))\n)[$__range:$__interval]) / (1h / $__interval) * (730h / $__range)",
     "legendFormat": "overhead"
    }
   ]
  },
  {
   "title": "Monthly Workload Cost (Live)",
   "type": "piechart",
   "description": "Workload cost of last 730h",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(\r\n    ((namespace_cpu_cost + namespace_memory_cost) OR on (namespace) sum by (namespace) (kube_namespace_labels) * 0) [730h:1m]) / 60",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum_over_time(sum_node_total_hourly_cost[730h:1m]) / 60\n-\nsum(sum_over_time(\n    ((namespace_cpu_cost + namespace_memory_cost) OR on (namespace) sum by (namespace) (kube_namespace_labels) * 0) [730h:1m]) / 60)",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Monthly Workload Cost (Estimation)",
   "type": "piechart",
   "description": "Estimation from current dashboard time range",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time((\n    (namespace_cpu_cost + namespace_memory_cost) OR on (namespace) sum by (namespace) (kube_namespace_labels) * 0\n)[$__range:$__interval]) / (1h / $__interval) * (730h / $__range)",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum_over_time((sum(node_total_hourly_cost))[$__range:$__interval]) / (1h / $__interval) * (730h / $__range)\r\n-\r\nsum(sum_over_time((\r\n    (namespace_cpu_cost + namespace_memory_cost) OR on (namespace) sum by (namespace) (kube_namespace_labels) * 0\r\n)[$__range:$__interval]) / (1h / $__interval) * (730h / $__range))",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Hourly Workload Cost by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expr": "sum_node_total_hourly_cost", "legendFormat": "Total" },
    {
     "expr": "namespace_cpu_cost + namespace_memory_cost",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Hourly Workload Cost by Container",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (namespace, container) (\n\tsum by (container,namespace, instance) (container_memory_allocation_bytes  / 1024 / 1024 / 1024)\n\t* on (instance) group_left() (\n\t\tnode_ram_hourly_cost{}\n\t\t# + on(node,instance_type) group_left()\n\t\t# label_replace(\n\t\t# \tkube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n\t\t# ) * 0\n\t)\n  + sum by (container, namespace, instance) (container_cpu_allocation)\n\t* on (instance) group_left() (\n\t\tnode_cpu_hourly_cost{}\n\t\t# + on(node, instance_type) group_left()\n\t\t# label_replace(\n\t\t# \tkube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n\t\t# ) * 0\n\t)\n)",
     "legendFormat": "{{namespace}} / {{container}}"
    }
   ]
  },
  {
   "title": "Monthly PV Cost by Namespace (Live)",
   "type": "piechart",
   "description": "PersistentVolume cost of last 730h",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n    sum_over_time((\n        sum by (persistentvolume) (pv_hourly_cost)\n        * on (persistentvolume) group_right() sum by (persistentvolume, namespace) (pod_pvc_allocation / 1024 / 1024 / 1024)\n    )[730h:1h])\n)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Monthly Overhead Cost (Live)",
   "type": "piechart",
   "description": "Overhead (cluster+LB) cost of last 730h",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(\n    sum(kubecost_load_balancer_cost OR on() vector(0))[730h:1h]\n)",
     "legendFormat": "lb"
    },
    {
     "expr": "sum_over_time(\n    sum(kubecost_cluster_management_cost)[730h:1h]\n)",
     "legendFormat": "cluster"
    }
   ]
  },
  {
   "title": "Monthly PV Cost by Namespace (Estimation)",
   "type": "piechart",
   "description": "Estimation from current dashboard time range",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(sum by (namespace) (\n    sum by (persistentvolume) (pv_hourly_cost)\n    * on (persistentvolume) group_right() sum by (persistentvolume, namespace) (pod_pvc_allocation / 1024 / 1024 / 1024)\n)[$__range:$__interval]) / (1h / $__interval) * (730h / $__range)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Monthly Overhead Cost (Estimation)",
   "type": "piechart",
   "description": "Estimation from current dashboard time range",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time((\n  sum(kubecost_load_balancer_cost OR on() vector(0))\n)[$__range:$__interval]) / (1h / $__interval) * (730h / $__range)",
     "legendFormat": "lb"
    },
    {
     "expr": "sum_over_time((\n  sum(kubecost_cluster_management_cost)\n)[$__range:$__interval]) / (1h / $__interval) * (730h / $__range)",
     "legendFormat": "cluster"
    }
   ]
  },
  { "title": "By Namespace $namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Monthly Workload Cost (Live)",
   "type": "piechart",
   "description": "Workload cost of last 730h",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(sum by (container) (\n    sum by (container, instance) (container_memory_allocation_bytes{namespace=\"$namespace\"})\n    * on(instance) group_left() (\n        node_ram_hourly_cost{} / 1024 / 1024 / 1024\n        + on(node,instance_type) group_left()\n            avg by (node, instance_type) (\n            label_replace\n            (\n                kube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n            ) * 0\n            )\n    )\n    + \n    sum by (container, instance) (container_cpu_allocation{namespace=\"$namespace\"})\n    * on(instance) group_left() (\n        node_cpu_hourly_cost{}\n        + on(node,instance_type) group_left()\n            avg by (node, instance_type) (\n            label_replace (\n                kube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n            ) * 0\n            )\n    )\n)[730h:1h])",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Monthly Workload Cost (Estimation)",
   "type": "piechart",
   "description": "Estimation from current dashboard time range",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time((\n    sum by (container) (\n        sum by (container, instance) (container_memory_allocation_bytes{namespace=\"$namespace\"})\n        * on(instance) group_left() (\n            node_ram_hourly_cost{} / 1024 / 1024 / 1024\n            + on(node,instance_type) group_left()\n                avg by (node, instance_type) (\n                label_replace\n                (\n                    kube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n                ) * 0\n                )\n        )\n        + \n        sum by (container, instance) (container_cpu_allocation{namespace=\"$namespace\"})\n        * on(instance) group_left() (\n            node_cpu_hourly_cost{}\n            + on(node,instance_type) group_left()\n                avg by (node, instance_type) (\n                label_replace (\n                    kube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n                ) * 0\n                )\n        )\n    ) OR on (container) sum by (container) (container_memory_allocation_bytes{namespace=\"$namespace\"}) * 0\n)[$__range:$__interval]) / (1h / $__interval) * (730h / $__range)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Hourly Workload Cost by Container",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (namespace, container) (\n\tsum by (container,namespace, instance) (container_memory_allocation_bytes{namespace=\"$namespace\"} / 1024 / 1024 / 1024)\n\t* on (instance) group_left() (\n\t\tnode_ram_hourly_cost{}\n\t\t# + on(node,instance_type) group_left()\n\t\t# label_replace(\n\t\t# \tkube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n\t\t# ) * 0\n\t)\n  + sum by (container, namespace, instance) (container_cpu_allocation{namespace=\"$namespace\"})\n\t* on (instance) group_left() (\n\t\tnode_cpu_hourly_cost{}\n\t\t# + on(node, instance_type) group_left()\n\t\t# label_replace(\n\t\t# \tkube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n\t\t# ) * 0\n\t)\n)",
     "legendFormat": "{{namespace}} / {{container}}"
    }
   ]
  },
  {
   "title": "Monthly PV Cost by Pod (Live)",
   "type": "piechart",
   "description": "PersistentVolume cost of last 730h",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (\n    sum_over_time((\n        sum by (persistentvolume) (pv_hourly_cost)\n        * on (persistentvolume) group_right() sum by (persistentvolume, pod) (pod_pvc_allocation{namespace=\"$namespace\"} / 1024 / 1024 / 1024)\n    )[730h:1m]) / 60\n)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Monthly PV Cost by Namespace (Estimation)",
   "type": "piechart",
   "description": "Estimation from current dashboard time range",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(sum by (pod) (\n    sum by (persistentvolume) (pv_hourly_cost)\n    * on (persistentvolume) group_right() sum by (persistentvolume, pod) (pod_pvc_allocation{namespace=\"$namespace\"} / 1024 / 1024 / 1024)\n    OR on (persistentvolume) sum by (persistentvolume) (pod_pvc_allocation{namespace=\"$namespace\"}) * 0\n)[$__range:$__interval]) / (1h / $__interval) * (730h / $__range)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  }
 ]
}