{
 "title": "Cluster / Persistent Volumes",
 "tags": [
  "kubernetes-mixin",
  "cluster-mixin"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\"}, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\"}, namespace)"
   },
   {
    "name": "volume",
    "label": "PersistentVolumeClaim",
    "query": "label_values(kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\"}, persistentvolumeclaim)"
   }
  ]
 },
 "panels": [
  {
   "title": "Volume Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  sum by (namespace, persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$volume\"})\n  -\n  sum by (namespace, persistentvolumeclaim) (kubelet_volume_stats_available_bytes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$volume\"})\n)\n/\nsum by (namespace, persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$volume\"})",
     "legendFormat": "{{ namespace }}/{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Volume inodes Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (namespace, persistentvolumeclaim) (kubelet_volume_stats_inodes_used{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$volume\"})\n/\nsum by (namespace, persistentvolumeclaim) (kubelet_volume_stats_inodes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$volume\"})",
     "legendFormat": "{{ namespace }}/{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Volume Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace, persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$volume\"})\n-\nsum by (namespace, persistentvolumeclaim) (kubelet_volume_stats_available_bytes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$volume\"})",
     "legendFormat": "{{ namespace }}/{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Volume inodes Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, persistentvolumeclaim) (kubelet_volume_stats_inodes_used{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$volume\"})",
     "legendFormat": "{{ namespace }}/{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Volume Fill Rate (1d)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "delta((\nsum by (namespace, persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$volume\"})\n-\nsum by (namespace, persistentvolumeclaim) (kubelet_volume_stats_available_bytes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$volume\"})\n)[24h])",
     "legendFormat": "{{ namespace }}/{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Volume Full ETA",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (namespace, persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$volume\"})\n/\nrate((\nsum by (namespace, persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$volume\"})\n-\nsum by (namespace, persistentvolumeclaim) (kubelet_volume_stats_available_bytes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$volume\"})\n)[24h])",
     "legendFormat": "{{ namespace }}/{{ persistentvolumeclaim }}"
    }
   ]
  }
 ]
}