{
 "title": "Cluster / Traefik Logs",
 "tags": [
  "traefik",
  "cluster-mixin"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "datasource",
    "query": "victoriametrics-logs-datasource"
   },
   {
    "name": "group_by",
    "query": "RequestHost : RequestHost, RequestHost\\, ServiceAddr : RequestHost\\, ServiceAddr"
   },
   {
    "name": "RequestHost",
    "query": {
     "query": "{namespace=\"traefik\"}"
    }
   },
   {
    "name": "ServiceAddr",
    "query": {
     "query": "{namespace=\"traefik\"} RequestHost:~\"$RequestHost\""
    }
   },
   {
    "name": "slow_threshold",
    "query": "50ms : 50000000, 100ms : 100000000, 250ms : 250000000, 500ms : 500000000, 1s : 1000000000, 2.5s : 2500000000, 5s : 5000000000, 10s : 10000000000"
   },
   { "name": "log_search" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Log-based Visualizations\n\n[LogsQL](https://docs.victoriametrics.com/victorialogs/logsql/) を用いたパネルたちです。\n実際のアクセスログからその都度集計しているため、正確な分、遅いです。\n\n表示期間 (Time Range) が長すぎるクエリは処理できません。\n必要な箇所だけを細かく確認するのに使ってください。"
   }
  },
  {
   "title": "System Logs",
   "type": "logs",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{namespace=\"traefik\"} Duration:\"\" | format <_msg><error>"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{namespace=\"traefik\"} Duration:!\"\" RequestHost:~\"$RequestHost\" ServiceAddr:~\"$ServiceAddr\" $log_search | stats count()"
    }
   ]
  },
  {
   "title": "Success (non-5xx) Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{namespace=\"traefik\"} Duration:!\"\" RequestHost:~\"$RequestHost\" ServiceAddr:~\"$ServiceAddr\" $log_search\r\n| stats\r\n  count() if (!DownstreamStatus:~\"5..\") \"non-5xx\",\r\n  count() all\r\n| math \"non-5xx\" / all as ratio\r\n| fields ratio"
    }
   ]
  },
  {
   "title": "Slow Requests (>=$slow_threshold)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{namespace=\"traefik\"} Duration:!\"\" RequestHost:~\"$RequestHost\" ServiceAddr:~\"$ServiceAddr\" $log_search\r\n| stats\r\n  count() if (Duration:>\"$slow_threshold\") slow,\r\n  count() all\r\n| math (slow / all) as ratio\r\n| fields ratio"
    }
   ]
  },
  {
   "title": "Failed (5xx) Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{namespace=\"traefik\"} Duration:!\"\" RequestHost:~\"$RequestHost\" ServiceAddr:~\"$ServiceAddr\" $log_search DownstreamStatus:~\"5..\" | stats count()"
    }
   ]
  },
  {
   "title": "Slow Requests (>=$slow_threshold)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{namespace=\"traefik\"} Duration:!\"\" RequestHost:~\"$RequestHost\" ServiceAddr:~\"$ServiceAddr\" $log_search Duration:>\"$slow_threshold\" | stats count() slow"
    }
   ]
  },
  {
   "title": "Access Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{namespace=\"traefik\"} Duration:!\"\" RequestHost:~\"$RequestHost\" ServiceAddr:~\"$ServiceAddr\" $log_search\r\n| math round(Duration / 1000000) as DurationMs\r\n| format \"[<ClientHost>] [<DownstreamStatus>] [<DurationMs>ms] <RequestMethod> <RequestHost><RequestPath>\""
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "{namespace=\"traefik\"} Duration:!\"\" RequestHost:~\"$RequestHost\" ServiceAddr:~\"$ServiceAddr\" $log_search | stats by ($group_by) rate()",
     "legendFormat": "{{ RequestHost }} / {{ ServiceAddr }}"
    }
   ]
  },
  {
   "title": "Request Rate (per user-agent)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "{namespace=\"traefik\"} Duration:!\"\" RequestHost:~\"$RequestHost\" ServiceAddr:~\"$ServiceAddr\" $log_search\n| stats\n  rate() if (request_User-Agent:~\"(?i)(?:iphone|ipad|ipod)\") iphone,\n  rate() if (request_User-Agent:~\"(?i)(?:android|blackberry|iemobile|opera mini|mobile)\") android,\n  rate() if (request_User-Agent:~\"(?i)(?:windows nt|macintosh|x11)\") desktop,\n  rate() all\n| math (all - iphone - android - desktop) as others\n| delete all"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "{namespace=\"traefik\"} Duration:!\"\" RequestHost:~\"$RequestHost\" ServiceAddr:~\"$ServiceAddr\" $log_search\r\n| stats by ($group_by)\r\n  quantile(0.99, Duration) p99,\r\n  quantile(0.90, Duration) p90,\r\n  median(Duration) p50",
     "legendFormat": "{{ __name__ }} / {{ RequestHost }} / {{ ServiceAddr }}"
    }
   ]
  },
  {
   "title": "Slow Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "{namespace=\"traefik\"} Duration:!\"\" RequestHost:~\"$RequestHost\" ServiceAddr:~\"$ServiceAddr\" $log_search\r\n| stats by ($group_by)\r\n  count() if (Duration:>10000000000) \"cnt-10\",\r\n  count() if (Duration:>5000000000) \"cnt-5\",\r\n  count() if (Duration:>250000000) \"cnt-2.5\",\r\n  count() if (Duration:>1000000000) \"cnt-1\",\r\n  count() if (Duration:>500000000) \"cnt-0.5\",\r\n  count() if (Duration:>250000000) \"cnt-0.25\",\r\n  count() if (Duration:>100000000) \"cnt-0.1\",\r\n  count() if (Duration:>50000000) \"cnt-0.05\",\r\n  count() all\r\n| math\r\n  (\"cnt-10\" / all) as \">10s\",\r\n  (\"cnt-5\" / all) as \">5s\",\r\n  (\"cnt-2.5\" / all) as \">2.5s\",\r\n  (\"cnt-1\" / all) as \">1s\",\r\n  (\"cnt-0.5\" / all) as \">0.5s\",\r\n  (\"cnt-0.25\" / all) as \">0.25s\",\r\n  (\"cnt-0.1\" / all) as \">0.1s\",\r\n  (\"cnt-0.05\" / all) as \">0.05s\"\r\n| fields _time, $group_by, \">10s\", \">5s\", \">2.5s\", \">1s\", \">0.5s\", \">0.25s\", \">0.1s\", \">0.05s\"",
     "legendFormat": "{{ __name__ }} / {{ RequestHost }} / {{ ServiceAddr }}"
    }
   ]
  },
  {
   "title": "Slow Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "{namespace=\"traefik\"} Duration:!\"\" RequestHost:~\"$RequestHost\" ServiceAddr:~\"$ServiceAddr\" $log_search\r\n| stats by ($group_by)\r\n  rate() if (Duration:>10000000000) \">10s\",\r\n  rate() if (Duration:>5000000000) \">5s\",\r\n  rate() if (Duration:>2500000000) \">2.5s\",\r\n  rate() if (Duration:>1000000000) \">1s\",\r\n  rate() if (Duration:>500000000) \">0.5s\",\r\n  rate() if (Duration:>250000000) \">0.25s\",\r\n  rate() if (Duration:>100000000) \">0.1s\",\r\n  rate() if (Duration:>50000000) \">0.05s\",\r\n  rate() all",
     "legendFormat": "{{ __name__ }} / {{ RequestHost }} / {{ ServiceAddr }}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Non-5xx Requests",
   "type": "timeseries",
   "description": "Average over 5m",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "{namespace=\"traefik\"} Duration:!\"\" RequestHost:~\"$RequestHost\" ServiceAddr:~\"$ServiceAddr\" $log_search\r\n| stats by ($group_by)\r\n  count() if (!DownstreamStatus:~\"5..\") \"non-5xx\",\r\n  count() all\r\n| math (\"non-5xx\" / all) as ratio\r\n| fields _time, ratio, $group_by",
     "legendFormat": "{{ RequestHost }} / {{ ServiceAddr }}"
    }
   ]
  },
  {
   "title": "Failed (5xx) Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "{namespace=\"traefik\"} Duration:!\"\" RequestHost:~\"$RequestHost\" ServiceAddr:~\"$ServiceAddr\" $log_search DownstreamStatus:~\"5..\"\n| stats by ($group_by) count()",
     "legendFormat": "{{ RequestHost }} / {{ ServiceAddr }}"
    }
   ]
  },
  {
   "title": "Requests by Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "{namespace=\"traefik\"} Duration:!\"\" RequestHost:~\"$RequestHost\" ServiceAddr:~\"$ServiceAddr\" $log_search\r\n| stats by ($group_by, DownstreamStatus) rate()",
     "legendFormat": "{{ RequestHost }} / {{ DownstreamStatus }}"
    }
   ]
  },
  {
   "title": "Requests by Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "{namespace=\"traefik\"} Duration:!\"\" RequestHost:~\"$RequestHost\" ServiceAddr:~\"$ServiceAddr\" $log_search\n| stats by ($group_by, DownstreamStatus) count()",
     "legendFormat": "{{ RequestHost }} / {{ DownstreamStatus }} / {{ ServiceAddr }}"
    }
   ]
  }
 ]
}